/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package convertidor.de.grados;

import javax.swing.JOptionPane;



/**
 *
 * @author Alex
 */
public class Convertidor extends javax.swing.JFrame {

    /**
     * Creates new form Convertidor
     */
    public Convertidor() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBox_Grados = new javax.swing.JComboBox();
        Txt_Grados = new javax.swing.JTextField();
        Label_Grados = new javax.swing.JLabel();
        Button_Convertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convertidor de Grados");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(" Celcius and Fahrenheit");

        ComboBox_Grados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBox_Grados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Convertir Grados", "Celcius a Fahrenheit", "Fahrenheit a Celcius" }));

        Txt_Grados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Label_Grados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Grados.setText("Grados");

        Button_Convertir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Convertir.setText("Convertir");
        Button_Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Button_Convertir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Txt_Grados, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Grados)
                            .addComponent(ComboBox_Grados, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Grados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Grados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Label_Grados)
                .addGap(27, 27, 27)
                .addComponent(Button_Convertir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void Grado(){
       String Grado;
       double res,f,c;
        
       if(Txt_Grados.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Ingrese un valor");
          Txt_Grados.requestFocus();
       }else{
           Grado = ComboBox_Grados.getSelectedItem().toString();
           
           if("Convertir Grados".equals(Grado)){
               JOptionPane.showMessageDialog(null, "Ingrese un metodo a convertir");
           }else{
              switch(Grado){
                  case "Celcius a Fahrenheit":
                      c = Double.parseDouble(Txt_Grados.getText());
                     res = (c*1.8)+32; 
                      Label_Grados.setText(res + " °F");
                      break;
                  case "Fahrenheit a Celcius":
                      f = Double.parseDouble(Txt_Grados.getText());
                      res = (f-32)/1.8;
                      Label_Grados.setText(res + " °C");
                      break;
              }
           }
       }
   }
    
    private void Button_ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConvertirActionPerformed
       Grado();
    }//GEN-LAST:event_Button_ConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Convertir;
    private javax.swing.JComboBox ComboBox_Grados;
    private javax.swing.JLabel Label_Grados;
    private javax.swing.JTextField Txt_Grados;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
